### ISSUE TITLE
Publish Overview detail errror

### ISSUE THREAD

**Issue by bergisch-media** [in2code-de/in2publish_core#19] opened 2017-03-24 11:34 UTC
Hi,

when clicking the small info "i" in Publish Overview > Page > "i" we suddenly do get a lot of DB SQL exceptions in the backend.

Somehow the tt_content.sys_language_uid seems to be empty - see the following exception trace and the failing SQL statement.

Do we have to configure languages in the backend for the publisher?

We use gridelements, so maybe the error is related to a gridelements hook or something?

Thank you in advance for checking ;)

```
caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'You have an error in your SQL syntax; check the manual that corresponds to y
      our MySQL server version for the right syntax to use near 'OR tt_content.tx_
      gridelements_container=0) ORDER BY tt_content.header, tt_conten' at line 1' (226 chars)
   lastBuiltQuery => 'SELECT * FROM tt_content WHERE uid LIKE "644" AND (tt_content.sys_language_u
      id = OR tt_content.tx_gridelements_container=0) ORDER BY tt_content.header,
       tt_content.uid' (167 chars)
   debug_backtrace => 'call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->run#2
      0 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Ht
      tp\BackendModuleRequestHandler->handleRequest#302 // TYPO3\CMS\Backend\Http\
      BackendModuleRequestHandler->dispatchModule#93 // TYPO3\CMS\Extbase\Core\Boo
      tstrap->run#215 // TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#193 // TY
      PO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest#206 // TYPO3\CM
      S\Extbase\Mvc\Dispatcher->dispatch#32 // TYPO3\CMS\Extbase\Mvc\Controller\Ac
      tionController->processRequest#86 // TYPO3\CMS\Extbase\Mvc\Controller\Action
      Controller->callActionMethod#176 // call_user_func_array#283 // In2code\In2p
      ublishCore\Controller\RecordController->detailAction# // In2code\In2publishC
      ore\Domain\Repository\CommonRepository->findByIdentifier#76 // In2code\In2pu
      blishCore\Domain\Repository\CommonRepository->convertToRecord#162 // In2code
      \In2publishCore\Domain\Factory\RecordFactory->makeInstance#1714 // In2code\I
      n2publishCore\Domain\Factory\RecordFactory->findRelatedRecordsForPageRecord#
      265 // In2code\In2publishCore\Domain\Repository\CommonRepository->enrichPage
      Record#341 // In2code\In2publishCore\Domain\Repository\CommonRepository->fin
      dByProperty#533 // In2code\In2publishCore\Domain\Repository\CommonRepository
      ->convertPropertyArraysToRecords#185 // In2code\In2publishCore\Domain\Reposi
      tory\CommonRepository->convertToRecord#359 // In2code\In2publishCore\Domain\
      Factory\RecordFactory->makeInstance#1714 // In2code\In2publishCore\Domain\Fa
      ctory\RecordFactory->findRelatedRecordsForContentRecord#267 // In2code\In2pu
      blishCore\Domain\Repository\CommonRepository->enrichRecordWithRelatedRecords
      #307 // In2code\In2publishCore\Domain\Repository\CommonRepository->fetchRela
      tedRecordsBySelect#400 // In2code\In2publishCore\Domain\Repository\BaseRepos
      itory->findPropertiesByProperty#1253 // TYPO3\CMS\Core\Database\DatabaseConn
      ection->exec_SELECTgetRows#159 // TYPO3\CMS\Core\Database\DatabaseConnection
      ->exec_SELECTquery#377 /...'
```

**Comment by vertexvaar** [comment] 2017-03-27 13:36
This is a bit weird, because we do not limit queries to gridelements container ;)
It seems that gridelements hooks into the DatabaseConnection to modify the query or executes its own queries after database operations (which is not visible because the stack trace is cut off).
Nevertheless in2publish does not require you to configure system languages. It only publishes them if they are present, but does not rely on them.

I will have a look at this, but since it's a problem with a 3rd party package the priority is rather low. Expect a response next week at the earliest.

**Comment by vertexvaar** [comment] 2017-04-06 08:43
Hi @bergisch-media,

i tried to reproduce this problem, but unfortunately i can't.
Please tell me how your system looks like, especially the versions of TYPO3, gridelements, in2publish_core and other extensions you installed, the sections `factory`, `debug` and `tca` of the in2publish_core configuration (as well as `workflow` and `features`, if you have them).
This might also help resolving #11.

**Comment by birgerstoeckelmann** [comment] 2017-04-07 09:02
Hi @vertexvaar,
first we will install the latest publisher version and gather some more debug information for you if the errors show up again.

**Comment by vertexvaar** [comment] 2017-05-08 08:47
Hi @bergisch-media, @birgerstoeckelmann 

it has been a while since your last response. Because this issue is missing a reply for a month i will close this, because it seems to be not important or fixed. If you still experience this issue please open another ticket with a full explanation and the missing details.

**Closed by vertexvaar** 2017-05-08 08:47 UTC
